/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.Usuario;
import static Presentacion.MetodosAuxPresentacion.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Breyner
 */
public class frmCompras extends javax.swing.JInternalFrame {
    
    Usuario usuario; 
    String[] camposTabla;
    String registroId;
    /**
     * Creates new form frmInventario
     */
    public frmCompras() {
        ArrayList<String[]> innerjoin =new ArrayList<>();
        innerjoin.add(new String[]{"i"});
        innerjoin.add(new String[]{"producto","p","codproducto","codigo"});
        usuario= new Usuario(new String[]{"inventario","El Inventario"},innerjoin);
        camposTabla =new String[]{"i.id","p.codigo","p.nombre","i.fecha","i.cantidad","i.precioin","i.precioout"};
        initComponents();
        LLenarTabla(tInventario, usuario.ReadAllInner(camposTabla));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pm = new javax.swing.JPopupMenu();
        pmInvDelete = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tInventario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecioIn = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPrecioOut = new javax.swing.JTextField();

        pmInvDelete.setText("Eliminar");
        pmInvDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmInvDeleteActionPerformed(evt);
            }
        });
        pm.add(pmInvDelete);

        setClosable(true);

        tInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tInventario);

        jLabel1.setText("Buscar");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel2.setText("Codigo Del Producto");

        jLabel3.setText("Cantidad");

        jLabel4.setText("Precio Unitario De Compra");

        txtIdProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdProductoKeyTyped(evt);
            }
        });

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        txtPrecioIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioInKeyTyped(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setText("Ingresar Registro");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Precio Unitario De Venta");

        txtPrecioOut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioOutKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(txtPrecioIn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtPrecioOut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(1, 1, 1)
                        .addComponent(txtPrecioOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptar)
                            .addComponent(btnCancelar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        LLenarTabla(tInventario , usuario.SearchInner(this.camposTabla, new String[]{"p.codigo","p.nombre"}, txtBuscar.getText()));
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void pmInvDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmInvDeleteActionPerformed
        // TODO add your handling code here:
        int op=JOptionPane.showConfirmDialog(null, "Realmente Desea eliminar El Registro "+this.registroId+"?", "Confirmar", JOptionPane.OK_CANCEL_OPTION , JOptionPane.QUESTION_MESSAGE);
        if(op==0){
            JOptionPane.showMessageDialog(null,usuario.Delete(new String[]{"id"}, new String[]{registroId}));
            LLenarTabla(tInventario, usuario.ReadAllInner(camposTabla));
        }
    }//GEN-LAST:event_pmInvDeleteActionPerformed

    private void tInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tInventarioMouseClicked
        // TODO add your handling code here:
        switch (evt.getButton()) {
            case 3://boton derecho
                String[] registro = GetRowDeJTable(tInventario, evt);
                this.registroId=registro[0];
                pm.show(this, evt.getX()+20, evt.getY()+80);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_tInventarioMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
         Limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if(!(CamposVacios())){
            String[] valores={null,txtIdProducto.getText(),
                usuario.getFechaActual(),
                txtCantidad.getText(),
                txtPrecioIn.getText(),
                txtPrecioOut.getText()};
            
            Usuario user=new Usuario(new String[]{"producto","El Producto"},null);
            if(user.TestRegistro(new String[]{"codigo"}, new String[]{txtIdProducto.getText()})){
                JOptionPane.showMessageDialog(null, usuario.Create(valores));
                LLenarTabla(tInventario, usuario.ReadAllInner(camposTabla));
            }else{
                JOptionPane.showMessageDialog(null, "El Producto No Existe");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Rellene Todos Los Campos");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtIdProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdProductoKeyTyped
        // TODO add your handling code here:
        SoloNumeros(evt);
    }//GEN-LAST:event_txtIdProductoKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        // TODO add your handling code here:
        SoloNumeros(evt);
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtPrecioInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioInKeyTyped
        // TODO add your handling code here:
        SoloNumeros(evt);
    }//GEN-LAST:event_txtPrecioInKeyTyped

    private void txtPrecioOutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioOutKeyTyped
        // TODO add your handling code here:
        SoloNumeros(evt);
    }//GEN-LAST:event_txtPrecioOutKeyTyped

    void Limpiar(){
        txtIdProducto.setText("");
        txtCantidad.setText("");
        txtPrecioIn.setText("");
        txtPrecioOut.setText("");
    }
    
    boolean CamposVacios(){
        boolean sw=false;
        if(txtIdProducto.getText().equals("")){
            sw=true;
        }
        if(txtCantidad.getText().equals("")){
            sw=true;
        }
        if(txtPrecioIn.getText().equals("")){
            sw=true;
        }
        if(txtPrecioOut.getText().equals("")){
            sw=true;
        }
        return sw;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPopupMenu pm;
    private javax.swing.JMenuItem pmInvDelete;
    private javax.swing.JTable tInventario;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtPrecioIn;
    private javax.swing.JTextField txtPrecioOut;
    // End of variables declaration//GEN-END:variables
}
