/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.Usuario;
import static Presentacion.MetodosAuxPresentacion.*;
import static Presentacion.frmCVendedor.desktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Breyner
 */
public class frmClientes extends javax.swing.JInternalFrame {
    
    Usuario cliente;
    String RegistroId;
    /**
     * Creates new form frmPClientes
     */
    public frmClientes() {
        cliente=new Usuario(new String[]{"cliente","El Cliente"},null);
        initComponents();
        LLenarTabla(tClientes, cliente.ReadAll(new String[]{"*"}));
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pm = new javax.swing.JPopupMenu();
        pmCliUpdate = new javax.swing.JMenuItem();
        pmCliDelete = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tClientes = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        pmCliUpdate.setText("Actualizar");
        pmCliUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmCliUpdateActionPerformed(evt);
            }
        });
        pm.add(pmCliUpdate);

        pmCliDelete.setText("Eliminar");
        pmCliDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmCliDeleteActionPerformed(evt);
            }
        });
        pm.add(pmCliDelete);

        setClosable(true);

        tClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tClientes.setCellSelectionEnabled(true);
        tClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tClientes);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel1.setText("Buscar");

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("*presione click derecho sobre un registro para ver mas opciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tClientesMouseClicked
        // TODO add your handling code here:
        switch (evt.getButton()) {
            case 3://boton derecho
                String registro[];
                registro = GetRowDeJTable(tClientes, evt);
                this.RegistroId=registro[0];
                pm.show(this, evt.getX()+20, evt.getY()+80);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_tClientesMouseClicked

    private void pmCliDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmCliDeleteActionPerformed
        // TODO add your handling code here:
        int op=JOptionPane.showConfirmDialog(null, "Realmente Desea Eliminar El Cliente (Cedula:"+this.RegistroId+")?", "Confirmar", JOptionPane.OK_CANCEL_OPTION , JOptionPane.QUESTION_MESSAGE);
        if(op==0){
            JOptionPane.showMessageDialog(null,cliente.Delete(new String[]{"cedula"}, new String[]{this.RegistroId}));
            LLenarTabla(tClientes, cliente.ReadAll(new String[]{"*"}));
        }
    }//GEN-LAST:event_pmCliDeleteActionPerformed

    private void pmCliUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmCliUpdateActionPerformed
        // TODO add your handling code here:
        MostrarFormularioInternoHH(this, desktopPane, new frmGCliente(this.RegistroId));
    }//GEN-LAST:event_pmCliUpdateActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        LLenarTabla(tClientes, cliente.Search(new String[]{"*"},new String[]{"cedula","nombre"},txtBuscar.getText()));
    }//GEN-LAST:event_txtBuscarKeyReleased

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu pm;
    private javax.swing.JMenuItem pmCliDelete;
    private javax.swing.JMenuItem pmCliUpdate;
    private javax.swing.JTable tClientes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
