/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.Usuario;
import Negocio.itemCombo;
import static Presentacion.MetodosAuxPresentacion.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Breyner
 */
public class frmFactura extends javax.swing.JInternalFrame {
    
    DefaultTableModel dtm;
    String CodigoSesion, CodigoCliente="";
    Usuario factura;
    int RegistroId;
    
    /**
     * Creates new form frmFactura
     * @param vCodigoSesion
     */
    public frmFactura(String vCodigoSesion) {
        this.CodigoSesion = vCodigoSesion;
        factura =new Usuario(new String[]{"factura","La Factura"},null);
        initComponents();
        txtUsuario.setText(this.CodigoSesion);
        CargarCombos();
        LLenarTabla(tFactura,cModelo());
    }
    
    DefaultTableModel cModelo(){
        dtm=new DefaultTableModel(null,new String[]{"IDINVENTARIO", "IDPRODUCTO", "NOMBRE", "CANTIDAD", "PRECIOc/u", "PRECIOTOTAL"}){public boolean isCellEditable(int rowIndex, int columIndex){return false;}};;
        return dtm;
    }
    
    void CargarCombos(){
        cbCategoria.setModel(factura.LlenarCombo("categoria", 0, 1));
        itemCombo vIdCategoria= (itemCombo)cbCategoria.getSelectedItem();
        cbProducto.setModel(factura.LlenarCombo("producto",0,1,"idcategoria",vIdCategoria.getId()));
        itemCombo vIdProducto= (itemCombo)cbProducto.getSelectedItem();
        cbPrecio.setModel(factura.LlenarComboPre("inventario i",0,5,new String[]{"i.codproducto","(i.cantidad - NVL((select SUM(cantidad) FROM detfactura d where i.id = d.idinventario),0))"},new String[]{vIdProducto.getId(),"0"}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pm = new javax.swing.JPopupMenu();
        miFacQui = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tFactura = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        lblResultado = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox();
        cbProducto = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnFacturar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbPrecio = new javax.swing.JComboBox();

        miFacQui.setText("Quitar");
        miFacQui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFacQuiActionPerformed(evt);
            }
        });
        pm.add(miFacQui);

        tFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tFacturaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tFactura);

        jLabel1.setText("Usuario");

        txtUsuario.setEnabled(false);

        jLabel2.setText("Cliente");

        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteKeyTyped(evt);
            }
        });

        lblResultado.setText("Resultado");

        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });

        cbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProductoActionPerformed(evt);
            }
        });

        jLabel4.setText("Categoria");

        jLabel5.setText("Producto");

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jLabel6.setText("Cantidad");

        btnFacturar.setText("Facturar");
        btnFacturar.setPreferredSize(new java.awt.Dimension(93, 23));
        btnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar Todo");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txtTotal.setEnabled(false);

        jLabel7.setText("Total");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel8.setText("Precio c/u");

        cbPrecio.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultado)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(btnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel8))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel6)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar))))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnFacturar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyReleased
        // TODO add your handling code here:
        Usuario cliente=new Usuario(new String[]{"cliente"},null);
        if(!"".equals(txtCliente.getText())){
            if(cliente.TestRegistro(new String[]{"cedula"},new String[]{txtCliente.getText()})){
                lblResultado.setText("Usuario Encontrado");
                CodigoCliente=lblResultado.getText();
            }else{
                lblResultado.setText("No Se Ha Encontrado El Usuario");
            }
        }
        
    }//GEN-LAST:event_txtClienteKeyReleased

    private void txtClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyTyped
        // TODO add your handling code here:
        SoloNumeros(evt);
    }//GEN-LAST:event_txtClienteKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        // TODO add your handling code here:
        SoloNumeros(evt);
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        //validar campos vacios
        if(CamposVacios()){
            JOptionPane.showMessageDialog(null, "Rellene Todos Los Campos");
        }else{
            if(!("".equals(CodigoCliente))){
                itemCombo vInventario= (itemCombo)cbPrecio.getSelectedItem();
                int canT = totalCantidad((DefaultTableModel)tFactura.getModel(), vInventario.getId());
                
                int tcan= canT +Integer.parseInt(txtCantidad.getText());
                String canDis=factura.testSuficiente(vInventario.getId());
                if(Integer.parseInt(canDis)>=tcan){
                    String[] datos=new String[6];
                    //idinventario
                    datos[0]=vInventario.getId();
                    //idproducto
                    itemCombo vProd= (itemCombo)cbProducto.getSelectedItem();
                    datos[1]=vProd.getId();
                    //nombre
                    datos[2]=vProd.toString();
                    //cantidad
                    datos[3]=txtCantidad.getText();
                    //preciou
                    itemCombo vPrec= (itemCombo)cbPrecio.getSelectedItem();
                    datos[4]=vPrec.toString();
                    //preciot
                    datos[5]=String.valueOf(Integer.parseInt(datos[3])*Integer.parseInt(datos[4]));
                    agregarfila(datos,vInventario.getId());
                    txtCliente.setEnabled(false);
                    txtTotal.setText(vTotal((DefaultTableModel)tFactura.getModel()));
                }else{
                    JOptionPane.showMessageDialog(null, "hay "+String.valueOf(Integer.parseInt(canDis)-canT)+" unidades disponibles");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Cliente Desconocido");
            }
            
        }
        //sumar al txt total
    }//GEN-LAST:event_btnAgregarActionPerformed

    void agregarfila(String[] datos, String vIdInve){
        boolean sw=false;
        if(dtm.getRowCount()>0){
            for(int i=0;i<dtm.getRowCount();i++){
                if(String.valueOf(dtm.getValueAt(i, 0)).equals(vIdInve)){
                    int res=Integer.parseInt(String.valueOf(dtm.getValueAt(i, 3)))+Integer.parseInt(datos[3]);
                    dtm.setValueAt((Object)res, i, 3);
                    int tot=Integer.parseInt(String.valueOf(dtm.getValueAt(i, 3)))*Integer.parseInt(String.valueOf(dtm.getValueAt(i, 4)));
                    dtm.setValueAt((Object)tot, i, 5);
                    sw=true;
                }
            }
            if(sw==false){
                dtm.addRow(datos);
            }
        }else{
            dtm.addRow(datos);
        }
        //
    }
    
    int totalCantidad(DefaultTableModel dtm, String vIdInve){
        //idinventario, idproducto, nombrepro, cantidad, precio, preciototal
        int acum=0;
        for(int i=0;i<dtm.getRowCount();i++){
            if(String.valueOf(dtm.getValueAt(i, 0)).equals(vIdInve)){
                acum+=Integer.parseInt(String.valueOf(dtm.getValueAt(i, 3)));
            }
        }
        return acum;
    }
    
    String vTotal(DefaultTableModel dtm){
        //idinventario, idproducto, nombrepro, cantidad, precio, preciototal
        int acum=0;
        for(int i=0;i<dtm.getRowCount();i++){
            acum+=Integer.parseInt(String.valueOf(dtm.getValueAt(i, 5)));
        }
        return String.valueOf(acum);
    }
    
    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed
        // TODO add your handling code here:
        if(tFactura.getRowCount()>0){
            prepararInsert();
        }
        //int idfac = INSERT INTO factura (id, idusuario, idcliente, fecha) VALUES (null,'"+txtUsuario.getText()+"','"+txtCliente.getText()+"','09/23/2015')
        //INSERT INTO detfactura (id, idfactura, idinventario, cantidad) VALUES (null,'"+idfac+"','"+Values[x]+"','"+Values[x]+"')
    }//GEN-LAST:event_btnFacturarActionPerformed

    void prepararInsert(){
        //idinventario, idproducto, nombrepro, cantidad, precio, preciototal
        Usuario vFactura= new Usuario(new String[]{"factura","La Factura"},null);
        String idFactura=vFactura.insertFactura(txtUsuario.getText(),txtCliente.getText());
        if(idFactura.equals(null)){
            JOptionPane.showMessageDialog(null, "No Se Inserto La Factura");
        }else{
            String[] vDatos=new String[4];
            vDatos[0]=null;
            vDatos[1]=idFactura;
            for(int i=0;i<tFactura.getRowCount();i++){
                vDatos[2]=String.valueOf(dtm.getValueAt(i, 0));
                vDatos[3]=String.valueOf(dtm.getValueAt(i, 3));
                Usuario vDetFactura= new Usuario(new String[]{"detfactura","La Factura"},null);
                vDetFactura.Create(vDatos);
            }
            JOptionPane.showMessageDialog(null, "La Compra Se Ha Efectuado Exitosamente");
            Limpiar();
        }

    }
    
    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
        // TODO add your handling code here:
        if(cbCategoria.getSelectedIndex()>=0){
            itemCombo vIdCategoria= (itemCombo)cbCategoria.getSelectedItem();
            cbProducto.setModel(factura.LlenarCombo("producto",0,1,"idcategoria",vIdCategoria.getId()));
            if(cbProducto.getSelectedIndex()>=0){
                itemCombo vIdProducto= (itemCombo)cbProducto.getSelectedItem();
                cbPrecio.setModel(factura.LlenarComboPre("inventario i",0,5,new String[]{"i.codproducto","(i.cantidad - NVL((select SUM(cantidad) FROM detfactura d where i.id = d.idinventario),0))"},new String[]{vIdProducto.getId(),"0"}));
            }else{
                cbPrecio.setModel(new DefaultComboBoxModel());
            }
        }
    }//GEN-LAST:event_cbCategoriaActionPerformed

    private void cbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProductoActionPerformed
        // TODO add your handling code here:
        if(cbProducto.getSelectedIndex()>=0){
            itemCombo vIdProducto= (itemCombo)cbProducto.getSelectedItem();
            cbPrecio.setModel(factura.LlenarComboPre("inventario i",0,5,new String[]{"i.codproducto","(i.cantidad - NVL((select SUM(cantidad) FROM detfactura d where i.id = d.idinventario),0))"},new String[]{vIdProducto.getId(),"0"}));
        }
    }//GEN-LAST:event_cbProductoActionPerformed

    private void tFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tFacturaMouseClicked
        // TODO add your handling code here:
        switch (evt.getButton()) {
            case 3://boton derecho
                
                this.RegistroId=tFactura.rowAtPoint(evt.getPoint());
                pm.show(this, evt.getX(), evt.getY()+240);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_tFacturaMouseClicked

    private void miFacQuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFacQuiActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dftm=(DefaultTableModel)tFactura.getModel();
        dftm.removeRow(RegistroId);
    }//GEN-LAST:event_miFacQuiActionPerformed

    void Limpiar(){
        lblResultado.setText("Resultado");
        cbPrecio.setSelectedIndex(0);
        txtCantidad.setText("");
        tFactura.removeAll();
        txtTotal.setText("");
        txtCliente.setText("");
        txtCliente.setEnabled(true);
        LLenarTabla(tFactura,cModelo());
    }
    
    boolean CamposVacios(){
        boolean sw=false;
        if(txtCliente.getText().equals("")){
            sw=true;
        }
        if(cbCategoria.getSelectedIndex()<0){
            sw=true;
        }
        if(cbProducto.getSelectedIndex()<0){
            sw=true;
        }
        if(cbPrecio.getSelectedIndex()<0){
            sw=true;
        }
        if(txtCantidad.getText().equals("")){
            sw=true;
        }
        return sw;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox cbCategoria;
    private javax.swing.JComboBox cbPrecio;
    private javax.swing.JComboBox cbProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JMenuItem miFacQui;
    private javax.swing.JPopupMenu pm;
    private javax.swing.JTable tFactura;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
