/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.Usuario;
import static Presentacion.MetodosAuxPresentacion.*;
import java.util.ArrayList;

/**
 *
 * @author Breyner
 */
public class frmInventario extends javax.swing.JInternalFrame {

    Usuario usuario;
    /**
     * Creates new form frmInventario
     * 
     * "SELECT i.codproducto, p.nombre,
     * (i.cantidad - (SELECT SUM(cantidad) total FROM detfactura d WHERE i.id = d.idinventario)) total 
     * FROM inventario i INNER JOIN producto p ON i.codproducto = p.codigo"
     */
    public frmInventario() {
        
        ArrayList<String[]> innerjoin =new ArrayList<>();
        innerjoin.add(new String[]{"i"});
        innerjoin.add(new String[]{"producto","p","codproducto","codigo"});
        usuario= new Usuario(new String[]{"inventario","El Inventario"},innerjoin);
        String[] camposTabla =new String[]{"i.codproducto","p.nombre","i.fecha FECHALOTE","(i.cantidad - NVL((SELECT SUM(cantidad) FROM detfactura d WHERE i.id = d.idinventario),0)) unidadesdisponibles"};
        initComponents();
        LLenarTabla(tInventario, usuario.ReadAllInner(camposTabla));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tInventario = new javax.swing.JTable();

        jScrollPane1.setViewportView(tInventario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tInventario;
    // End of variables declaration//GEN-END:variables
}
