/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.Usuario;
import Negocio.itemCombo;
import static Presentacion.MetodosAuxPresentacion.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Breyner
 */
public class frmProductos extends javax.swing.JInternalFrame {
    
    Usuario usuario;
    String[] camposTabla;
    boolean create=true;
    String Codigo;
    /**
     * Creates new form frmProductos
 "SELECT p.Codigo, p.nombre, p.descripcion, c.nombre categoria 
 FROM producto p INNER JOIN categoria c ON p.idcategoria = c.id"
     */
    public frmProductos() {
        ArrayList<String[]> innerjoin =new ArrayList<>();
        innerjoin.add(new String[]{"p"});
        innerjoin.add(new String[]{"categoria","c","idcategoria","id"});
        usuario= new Usuario(new String[]{"producto","El Producto"},innerjoin);
        camposTabla = new String[]{"p.codigo", "p.nombre", "p.descripcion", "c.nombre categoria"};
        initComponents();
        
        LLenarTabla(tProductos, usuario.ReadAllInner(camposTabla));
        cbCategoria.setModel(usuario.LlenarCombo("categoria", 0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pm = new javax.swing.JPopupMenu();
        pmProUpdate = new javax.swing.JMenuItem();
        pmProDelete = new javax.swing.JMenuItem();
        jLabel4 = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnNewCat = new javax.swing.JButton();

        pmProUpdate.setText("Actualizar");
        pmProUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmProUpdateActionPerformed(evt);
            }
        });
        pm.add(pmProUpdate);

        pmProDelete.setText("Eliminar");
        pmProDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmProDeleteActionPerformed(evt);
            }
        });
        pm.add(pmProDelete);

        jLabel4.setText("Buscar");

        tProductos.setCellSelectionEnabled(true);
        tProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tProductos);

        jLabel1.setText("Nombre");

        jLabel2.setText("Descripcion");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setText("Nuevo Producto");

        jLabel3.setText("Categoria");

        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("<html>*presione click derecho sobre un <br> registro para ver mas opciones");

        jLabel6.setText("Codigo");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        taDescripcion.setColumns(20);
        taDescripcion.setRows(5);
        taDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                taDescripcionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(taDescripcion);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNewCat.setText("+");
        btnNewCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 47, Short.MAX_VALUE)
                                .addComponent(btnAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNewCat))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(txtNombre)
                                    .addComponent(txtCodigo))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitulo)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNewCat)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptar)
                            .addComponent(btnCancelar))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tProductosMouseClicked
        // TODO add your handling code here:
        switch (evt.getButton()) {
            case 3://boton derecho
            String registro[] = GetRowDeJTable(tProductos, evt);
            this.Codigo=registro[0];
            pm.show(this, evt.getX()+20, evt.getY()+80);
            break;
            default:
            break;
        }
    }//GEN-LAST:event_tProductosMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        LLenarTabla(tProductos, usuario.SearchInner(this.camposTabla, new String[]{"p.codigo","p.nombre"}, txtBuscar.getText()));
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
        SoloNumeros(evt);
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void taDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taDescripcionKeyTyped
        // TODO add your handling code here:
        NumeroDeCaracteres(taDescripcion, 255, evt);
    }//GEN-LAST:event_taDescripcionKeyTyped

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        itemCombo ic=(itemCombo)cbCategoria.getSelectedItem();
        if(!(CamposVacios())){//create
            String[] valores= {txtCodigo.getText(),
                txtNombre.getText(),
                taDescripcion.getText(),
                ic.getId()};
            if(create){//insert
                if(usuario.TestRegistro(new String[]{"codigo"}, new String[]{txtCodigo.getText()})){
                    JOptionPane.showMessageDialog(null, "Ya Existe Un Producto Con Ese Codigo");
                }else{
                    JOptionPane.showMessageDialog(null, usuario.Create(valores));
                    LimpiarCampos();
                }
            }else{//update
                int op=JOptionPane.showConfirmDialog(null, "Realmente Desea Actualizar El Producto Codigo:"+this.Codigo+"?", "Confirmar", JOptionPane.OK_CANCEL_OPTION , JOptionPane.QUESTION_MESSAGE);
                if(op==0){
                    String[] campos= new String[]{"codigo", "nombre", "descripcion", "idcategoria"};
                    if(usuario.TestRegistroUpdate(campos, valores)){
                        JOptionPane.showMessageDialog(null, "Ya Existe Un Producto Con Esos Atributos");
                    }else{
                        valores[0]=null;
                        JOptionPane.showMessageDialog(null, usuario.Update(valores,new String[]{"codigo"},new String[]{txtCodigo.getText()}));
                        LimpiarCampos();
                    }
                }
            }
            LLenarTabla(tProductos, usuario.ReadAllInner(camposTabla));
        }else{
            JOptionPane.showMessageDialog(null, "Rellene Todos Los Campos");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        LimpiarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNewCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCatActionPerformed
        // TODO add your handling code here:
        String vNewCategoria =JOptionPane.showInputDialog(null, "Ingrese El Nombre De La Nueva Categoria", "Agregar Categoria", JOptionPane.INFORMATION_MESSAGE);
        if(vNewCategoria!=null && !"".equals(vNewCategoria)){

            Usuario user= new Usuario(new String[]{"categoria","La categoria"},null);
            if(user.TestRegistro(new String[]{"nombre"},new String[]{vNewCategoria})){
                JOptionPane.showMessageDialog(null, "Ya Existe Una Categoria Con Ese Nombre");
            }else{
                JOptionPane.showMessageDialog(null, user.Create(new String[]{null,vNewCategoria}));
                cbCategoria.setModel(usuario.LlenarCombo("categoria", 0, 1));
            }

        }
    }//GEN-LAST:event_btnNewCatActionPerformed

    private void pmProUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmProUpdateActionPerformed
        // TODO add your handling code here:
        lblTitulo.setText("Actualizar Producto");
        String[] registro=usuario.getRegistro("codigo", this.Codigo);
        txtCodigo.setText(registro[0]);
        txtCodigo.setEnabled(false);
        txtNombre.setText(registro[1]);
        taDescripcion.setText(registro[2]);
        SeleccionCombo(cbCategoria, registro[3]);
        create=false;
    }//GEN-LAST:event_pmProUpdateActionPerformed

    private void pmProDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmProDeleteActionPerformed
        // TODO add your handling code here:
        int op=JOptionPane.showConfirmDialog(null, "Realmente Desea eliminar El Producto Codigo:"+this.Codigo+"?", "Confirmar", JOptionPane.OK_CANCEL_OPTION , JOptionPane.QUESTION_MESSAGE);
        if(op==0){
            JOptionPane.showMessageDialog(null,usuario.Delete(new String[]{"codigo"}, new String[]{this.Codigo}));
            LLenarTabla(tProductos, usuario.ReadAllInner(camposTabla));
        }
    }//GEN-LAST:event_pmProDeleteActionPerformed

    boolean CamposVacios(){
        boolean sw=false;
        if(txtCodigo.getText().equals("")){
            sw=true;
        }
        if(taDescripcion.getText().equals("")){
            sw=true;
        }
        if(txtNombre.getText().equals("")){
            sw=true;
        }
        if(cbCategoria.getSelectedIndex()<0){
            sw=true;
        }
        return sw;
    }
    
    void LimpiarCampos(){
        txtCodigo.setText("");
        taDescripcion.setText("");
        txtNombre.setText("");
        cbCategoria.setSelectedIndex(-1);
        create=true;
        txtCodigo.setEnabled(true);
        lblTitulo.setText("Nuevo Producto");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNewCat;
    private javax.swing.JComboBox cbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPopupMenu pm;
    private javax.swing.JMenuItem pmProDelete;
    private javax.swing.JMenuItem pmProUpdate;
    private javax.swing.JTable tProductos;
    private javax.swing.JTextArea taDescripcion;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
