/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.util.ArrayList;
import static Presentacion.MetodosAuxPresentacion.*;
import Negocio.Usuario;
import Negocio.itemCombo;
import javax.swing.JOptionPane;
/**
 *
 * @author Breyner
 */
public class frmUsuarios extends javax.swing.JInternalFrame {

    Usuario usuario;
    String[] camposTabla;
    boolean create=true;
    String registroId=null;
    
    /**
     * Creates new form frmUsuarios
     */
    public frmUsuarios() {
        ArrayList<String[]> innerjoin =new ArrayList<>();
        innerjoin.add(new String[]{"u"});
        innerjoin.add(new String[]{"tipousuario","t","idtipo","id"});
        innerjoin.add(new String[]{"estadousuario","e","idestado","id"});
        usuario= new Usuario(new String[]{"usuario","El Usuario"},innerjoin);
        camposTabla =new String[]{"u.id","u.usuario","u.nombre","t.nombre tipo","e.nombre estado"};
        initComponents();
        
        LLenarTabla(tUsuarios, usuario.ReadAllInner(camposTabla));
        cbTipo.setModel(usuario.LlenarCombo("tipousuario", 0, 1));
        cbEstado.setModel(usuario.LlenarCombo("estadousuario", 0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pm = new javax.swing.JPopupMenu();
        pmUsuUpdate = new javax.swing.JMenuItem();
        pmUsuDelete = new javax.swing.JMenuItem();
        btnAceptar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        txtContrasena2 = new javax.swing.JPasswordField();
        cbTipo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tUsuarios = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();

        pmUsuUpdate.setText("Actualizar");
        pmUsuUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmUsuUpdateActionPerformed(evt);
            }
        });
        pm.add(pmUsuUpdate);

        pmUsuDelete.setText("Eliminar");
        pmUsuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmUsuDeleteActionPerformed(evt);
            }
        });
        pm.add(pmUsuDelete);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel9.setText("Contraseña");

        lblTitulo.setText("Crear Usuario");

        jLabel1.setText("Usuario");

        jLabel2.setText("Confirmar Contraseña");

        jLabel10.setText("Buscar");

        jLabel3.setText("Nombre");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel7.setText("Tipo Usuario");

        tUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tUsuarios);

        jLabel8.setText("Estado Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtContrasena)
                                                .addComponent(txtUsuario)
                                                .addComponent(txtContrasena2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtNombre)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(btnAceptar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCancelar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addComponent(lblTitulo)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitulo)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtContrasena2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptar)
                            .addComponent(btnCancelar))
                        .addGap(55, 55, 55))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        itemCombo ic=(itemCombo)cbTipo.getSelectedItem();
        itemCombo ic2=(itemCombo)cbEstado.getSelectedItem();
        if(!(CamposVacios())){
            if(String.valueOf(txtContrasena.getPassword()).equals(String.valueOf(txtContrasena2.getPassword()))){
            String[] valores= {null,txtUsuario.getText(),
                String.valueOf(txtContrasena.getPassword()),
                txtNombre.getText(),
                ic.getId(),
                ic2.getId()};
            if(create){//insert
                if(usuario.TestRegistro(new String[]{"usuario"}, new String[]{valores[0]})){
                    JOptionPane.showMessageDialog(null, "Digite Otro Usuario");
                }else{
                    JOptionPane.showMessageDialog(null, usuario.Create(valores));
                    LimpiarCampos();
                }
            }else{//update
                int op=JOptionPane.showConfirmDialog(null, "Realmente Desea Actualizar El Usuario id:"+registroId+"?", "Confirmar", JOptionPane.OK_CANCEL_OPTION , JOptionPane.QUESTION_MESSAGE);
                if(op==0){
                    if(usuario.TestRegistroUpdate(new String[]{"id","usuario"}, new String[]{registroId,valores[1]})){
                        JOptionPane.showMessageDialog(null, "Digite Otro Usuario");
                    }else{
                        JOptionPane.showMessageDialog(null, usuario.Update(valores, new String[]{"id"}, new String[]{registroId}));
                        LimpiarCampos();
                    } 
                }
            }
            LLenarTabla(tUsuarios, usuario.ReadAllInner(camposTabla));
        }else{
                JOptionPane.showMessageDialog(null, "Las Contraseñas No Coinciden");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Rellene Todos Los Campos");
        }
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        LimpiarCampos();
        create=true;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        LLenarTabla(tUsuarios, usuario.SearchInner(this.camposTabla, new String[]{"u.usuario","u.nombre"}, txtBuscar.getText()));
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tUsuariosMouseClicked
        // TODO add your handling code here:
        switch (evt.getButton()) {
            case 3://boton derecho
                String registro[];
                registro = GetRowDeJTable(tUsuarios, evt);
                registroId=registro[0];
                pm.show(this, evt.getX()+20, evt.getY()+80);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_tUsuariosMouseClicked

    private void pmUsuUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmUsuUpdateActionPerformed
        // TODO add your handling code here:
        lblTitulo.setText("Actualizar Usuario");
        String[] registro=usuario.getRegistro("id", this.registroId);
        txtUsuario.setText(registro[1]);
        txtContrasena.setText(registro[2]);
        txtContrasena2.setText(registro[2]);
        txtNombre.setText(registro[3]);
        SeleccionCombo(cbTipo, registro[4]);
        SeleccionCombo(cbEstado, registro[5]);
        create=false;
    }//GEN-LAST:event_pmUsuUpdateActionPerformed

    private void pmUsuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmUsuDeleteActionPerformed
        // TODO add your handling code here:
        int op=JOptionPane.showConfirmDialog(null, "Realmente Desea eliminar El Usuario?", "Confirmar", JOptionPane.OK_CANCEL_OPTION , JOptionPane.QUESTION_MESSAGE);
        if(op==0){
            JOptionPane.showMessageDialog(null,usuario.Delete(new String[]{"id"}, new String[]{registroId}));
            LLenarTabla(tUsuarios, usuario.ReadAllInner(camposTabla));
        }
    }//GEN-LAST:event_pmUsuDeleteActionPerformed

    boolean CamposVacios(){
        boolean sw=false;
        if(txtUsuario.getText().equals("")){
            sw=true;
        }
        if(String.valueOf(txtContrasena.getPassword()).equals("")){
            sw=true;
        }
        if(String.valueOf(txtContrasena2.getPassword()).equals("")){
            sw=true;
        }
        if(txtNombre.getText().equals("")){
            sw=true;
        }
        if(cbTipo.getSelectedIndex()<0){
            sw=true;
        }
        if(cbEstado.getSelectedIndex()<0){
            sw=true;
        }
        return sw;
    }
    
    void LimpiarCampos(){
        txtUsuario.setText("");
        txtContrasena.setText("");
        txtContrasena2.setText("");
        txtNombre.setText("");
        cbTipo.setSelectedIndex(-1);
        cbEstado.setSelectedIndex(-1);
        lblTitulo.setText("Crear Usuario");
        create=true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cbEstado;
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPopupMenu pm;
    private javax.swing.JMenuItem pmUsuDelete;
    private javax.swing.JMenuItem pmUsuUpdate;
    private javax.swing.JTable tUsuarios;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JPasswordField txtContrasena2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
