/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.Usuario;
import static Presentacion.MetodosAuxPresentacion.*;
import static Presentacion.frmCAdministrador.desktopPane;
import java.util.ArrayList;

/**
 *
 * @author Breyner
 */
public class frmVentas extends javax.swing.JInternalFrame {

    Usuario usuario;
    String[] camposTabla;
    String idFactura;
    /**
     * Creates new form frmVentas
     * "SELECT  id,  usuario, , ,
     *  
     * 
     */
    public frmVentas() {
        ArrayList<String[]> innerjoin =new ArrayList<>();
        innerjoin.add(new String[]{"f"});
        innerjoin.add(new String[]{"cliente","c","idcliente","cedula"});
        innerjoin.add(new String[]{"usuario","u","idusuario","id"});
        usuario= new Usuario(new String[]{"factura","La Factura"},innerjoin);
        camposTabla =new String[]{"f.id id","u.id usuario","c.cedula cliente","f.fecha","(SELECT SUM(d.cantidad * i.precioout) total FROM detfactura d INNER JOIN inventario i On d.idinventario= i.id INNER JOIN producto p On i.codproducto= p.codigo WHERE f.id = d.idfactura)as total"};
        initComponents();
        
        LLenarTabla(tVentas, usuario.ReadAllInner(camposTabla));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pm = new javax.swing.JPopupMenu();
        pmDetalles = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tVentas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        pmDetalles.setText("Detalles");
        pmDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmDetallesActionPerformed(evt);
            }
        });
        pm.add(pmDetalles);

        tVentas.setToolTipText("");
        tVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tVentas);

        jLabel1.setText("Buscar");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tVentasMouseClicked
        // TODO add your handling code here:
        switch (evt.getButton()) {
            case 3://boton derecho
                String registro[];
                registro = GetRowDeJTable(tVentas, evt);
                this.idFactura=registro[0];
                pm.show(this, evt.getX()+20, evt.getY()+80);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_tVentasMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        LLenarTabla(tVentas, usuario.SearchInner(this.camposTabla, new String[]{"u.usuario","c.cedula"}, txtBuscar.getText()));
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void pmDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmDetallesActionPerformed
        // TODO add your handling code here:
        MostrarFormularioInternoHH(this, desktopPane, new frmDetVenta(this.idFactura));
    }//GEN-LAST:event_pmDetallesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu pm;
    private javax.swing.JMenuItem pmDetalles;
    private javax.swing.JTable tVentas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
